# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 794400a3f99f03cabc194d704491aa6e84f8ab8070d626ac37f61b796721064dd44b4d3e637bd80010182679cb39967d6ea1e671e8e8d4b1a6c02c5d048f8f41

test:
  secret_key_base: 1f4e4684d0b3ec871c815f8f8ab1a3df0b96e261cff1b71ad1e88ca23a21312c8165d178be2c6784a6616578d7485be20e29ebc1fad0da13fc07dcfb7d400537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
